// utils/constants.ts
export const REGION_PRICING: Record<string, number> = {
  'us-central1': 6.25,
  'us-east1': 6.25,
  'us-east4': 6.25,
  'us-east5': 6.25,
  'us-west1': 6.25,
  'us-west2': 8.44,
  'us-west3': 8.44,
  'us-west4': 6.25,
  'us-south1': 6.25,
  'northamerica-northeast1': 6.56,
  'northamerica-northeast2': 6.56,
  'southamerica-east1': 11.25,
  'southamerica-west1': 8.94,
  'europe-west1': 7.50,
  'europe-west2': 7.81,
  'europe-west3': 8.13,
  'europe-west4': 7.50,
  'europe-west6': 8.75,
  'europe-west8': 7.81,
  'europe-west9': 7.81,
  'europe-west10': 9.63,
  'europe-west12': 7.81,
  'europe-north1': 7.50,
  'europe-central2': 8.13,
  'europe-southwest1': 7.81,
  'me-central1': 7.50,
  'me-central2': 10.00,
  'africa-south1': 8.18,
  'asia-east1': 7.19,
  'asia-east2': 8.75,
  'asia-southeast1': 8.44,
  'asia-southeast2': 7.50,
  'asia-south1': 7.50,
  'asia-south2': 7.50,
  'asia-northeast1': 7.50,
  'asia-northeast2': 7.50,
  'asia-northeast3': 7.50,
  'australia-southeast1': 8.13,
  'australia-southeast2': 8.13,
  'us': 6.25,
  'eu': 6.25,
  // BigQuery Omni Regions ($9.125 per TiB)
  'aws-ap-northeast-2': 10.00,
  'aws-ap-southeast-2': 10.55,
  'aws-eu-central-1': 10.16,
  'aws-eu-west-1': 9.37,
  'aws-us-east-1': 7.81,
  'aws-us-west-2': 7.81,
  'azure-us-east2': 7.81,
  'azure-westus2': 9.125,
  // Static Price Groups (Fallback)
  'price-6.25': 6.25,
  'price-7.50': 7.50,
  'price-8.13': 8.13,
  'price-9.125': 9.125,
};

export const REGION_LABELS: Record<string, string> = {
  'us-central1': 'Iowa',
  'us-east1': 'South Carolina',
  'us-east4': 'Northern Virginia',
  'us-east5': 'Columbus',
  'us-west1': 'Oregon',
  'us-west2': 'Los Angeles',
  'us-west3': 'Salt Lake City',
  'us-west4': 'Las Vegas',
  'us-south1': 'Dallas',
  'northamerica-northeast1': 'Montreal',
  'northamerica-northeast2': 'Toronto',
  'southamerica-east1': 'São Paulo',
  'southamerica-west1': 'Santiago',
  'europe-west1': 'Belgium',
  'europe-west2': 'London',
  'europe-west3': 'Frankfurt',
  'europe-west4': 'Netherlands',
  'europe-west6': 'Zurich',
  'europe-west8': 'Milan',
  'europe-west9': 'Paris',
  'europe-west10': 'Berlin',
  'europe-west12': 'Turin',
  'europe-north1': 'Finland',
  'europe-central2': 'Warsaw',
  'europe-southwest1': 'Madrid',
  'me-central1': 'Doha',
  'me-central2': 'Dammam',
  'africa-south1': 'Johannesburg',
  'asia-east1': 'Taiwan',
  'asia-east2': 'Hong Kong',
  'asia-southeast1': 'Singapore',
  'asia-southeast2': 'Jakarta',
  'asia-south1': 'Mumbai',
  'asia-south2': 'Delhi',
  'asia-northeast1': 'Tokyo',
  'asia-northeast2': 'Osaka',
  'asia-northeast3': 'Seoul',
  'australia-southeast1': 'Sydney',
  'australia-southeast2': 'Melbourne',
  'us': 'US Multi-region',
  'eu': 'EU Multi-region',
  'aws-ap-northeast-2': 'Seoul (AWS)',
  'aws-ap-southeast-2': 'Sydney (AWS)',
  'aws-eu-central-1': 'Frankfurt (AWS)',
  'aws-eu-west-1': 'Ireland (AWS)',
  'aws-us-east-1': 'Northern Virginia (AWS)',
  'aws-us-west-2': 'Oregon (AWS)',
  'azure-us-east2': 'Virginia (Azure)',
  'azure-westus2': 'Washington (Azure)',
  'price-6.25': 'Static Price',
  'price-7.50': 'Static Price',
  'price-8.13': 'Static Price',
  'price-9.125': 'Static Price',
};

export const REGIONS = Object.keys(REGION_PRICING);

export const CURRENCIES = [
  { code: 'usd', symbol: '$', locale: 'en-US' },
  { code: 'eur', symbol: '€', locale: 'de-DE' },
  { code: 'gbp', symbol: '£', locale: 'en-GB' },
  { code: 'jpy', symbol: '¥', locale: 'ja-JP' },
  { code: 'idr', symbol: 'Rp', locale: 'id-ID' },
  { code: 'cny', symbol: '¥', locale: 'zh-CN' },
  { code: 'aud', symbol: 'A$', locale: 'en-AU' },
  { code: 'sgd', symbol: 'S$', locale: 'en-SG' },
];

export const DEFAULT_REGION = 'us';
export const DEFAULT_CURRENCY = 'usd';
export const FALLBACK_PRICE = 6.25;
